name: Mirror to Codeberg

on:
  push:
    branches: [ "main", "master" ] # Jalankan otomatis saat ada push di branch main atau master

jobs:
  codeberg-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Mengambil seluruh riwayat commit agar sinkronisasi sempurna

      - name: Push to Codeberg
        run: |
          # Menambahkan Codeberg sebagai remote mirror
          # Ganti USERNAME dan NAMA_REPO di bawah ini
          git remote add codeberg https://x-access-token:${{ secrets.CODEBERG_TOKEN }}@codeberg.org/rydevs29/RifyShield.git
          
          # Mengirim semua branch dan tag ke Codeberg
          git push --force --mirror codeberg
          
