name: Sync Blocklist Sources

on:
  schedule:
    - cron: "0 0 * * 0"   # Jalan otomatis tiap Minggu jam 00:00 UTC
  workflow_dispatch:       # Bisa dijalankan manual

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download external blocklists
        run: |
          mkdir -p filters/blocklist
          
          # 1. Download Hagezi Ultimate (Sumber Utama)
          curl -sL https://raw.githubusercontent.com/hagezi/dns-blocklists/refs/heads/main/domains/ultimate.txt > filters/blocklist/ultimate.txt

          # 2. Download TrustPositif Gambling (Link Terbaru)
          curl -sL https://raw.githubusercontent.com/alsyundawy/TrustPositif/refs/heads/main/alsyundawy_gambling.txt > trust-temp.txt

          # 3. Gabungkan Keduanya ke blocklist.txt & hapus duplikat
          cat filters/blocklist/ultimate.txt trust-temp.txt | sort -u > filters/blocklist/blocklist.txt

          # Hapus file temp
          rm trust-temp.txt

      - name: Commit & Push changes
        run: |
          git config --global user.name "RifqyBot"
          git config --global user.email "bot@rifqyshield.local"
          
          # Update file yang diperlukan saja
          git add filters/blocklist/ultimate.txt filters/blocklist/blocklist.txt
          
          git commit -m "Sync: Hagezi Normal + Alsyundawy Gambling" || echo "No changes to commit"
          git push
