name: RifqyShield Auto-Build

on:
  push:
    branches: [ "main" ]
    # Workflow hanya akan menyala otomatis jika yang diedit adalah script, whitelist, atau folder filters.
    # Ini mencegah mesin menyala berulang-ulang tanpa henti (looping).
    paths:
      - 'build.py'
      - 'whitelist.txt'
      - 'filters/**'
  schedule:
    # Berjalan setiap hari jam 00:00 UTC (07:00 Pagi WIB)
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Naik ke 3.10 agar lebih ngebut

      - name: Run Build Script (All-in-One Engine)
        run: python build.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "RifqyBot Engine"
          git config --global user.email "bot@rifqyshield.local"
          
          # Merekam semua perubahan (tambah/hapus) di dalam folder output/
          git add --all output/
          
          # Mengecek apakah ada perubahan. Jika ada, langsung push ke GitHub
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update: Sinkronisasi Blocklists [skip ci]" && git push)
